#!/usr/bin/env bash
# env.sh — Shared environment for all hooks
#
# TEMPLATE VERSION (claude-backup):
#   Contains ${PROJECT_REPO} / ${PLANNING_REPO} placeholders.
#   /onboard replaces these with literal paths when setting up a developer's machine.
#
# RUNTIME VERSION (project/.claude/hooks/):
#   Contains resolved literal paths. Generated by /onboard.
#   Do NOT edit manually — re-run /onboard to reconfigure.
#
# Usage (from any hook script):
#   source "$(dirname "$0")/env.sh"

PROJECT_REPO="${PROJECT_REPO}"
PLANNING_REPO="${PLANNING_REPO}"
SOURCE_REPO="${SOURCE_REPO}"
DEVELOPER="UNCONFIGURED"

# Derived paths used by multiple hooks
PLANNING_DIR="${PLANNING_REPO}"
STATE_FILE="${PLANNING_DIR}/main/STATE.md"
HANDOVER_DIR="${PLANNING_DIR}/handovers"
DECISIONS_DIR="${PLANNING_DIR}/decisions"
BACKUP_COMMANDS_DIR="${PLANNING_DIR}/claude-backup/commands"

# --- Validation helper ---
# Call this from hooks that need the planning repo to exist.
# Usage: require_planning_repo || exit 0
require_planning_repo() {
  if [[ -z "$PLANNING_REPO" || "$PLANNING_REPO" == '${PLANNING_REPO}' ]]; then
    echo "Hook skipped: env.sh not configured. Run /onboard." >&2
    return 1
  fi
  if [[ ! -d "$PLANNING_REPO" ]]; then
    echo "Hook skipped: PLANNING_REPO not found at $PLANNING_REPO" >&2
    return 1
  fi
  return 0
}

# --- Project-specific guardrails (defaults) ---
# Override in $PLANNING_DIR/main/hooks-config.sh (git-tracked, shared by all devs).
# Space-separated directory names relative to project root.
PROTECTED_PATHS=""
# Case-insensitive patterns matched anywhere in the path (space-separated).
PROTECTED_PATTERNS=""
# Set to "true" to block git commit commands.
BLOCK_GIT_COMMIT="false"

# Source project-specific overrides if they exist
_HOOKS_CONFIG="${PLANNING_DIR}/main/hooks-config.sh"
if [[ -f "$_HOOKS_CONFIG" ]]; then
  source "$_HOOKS_CONFIG"
fi
