#!/usr/bin/env bash
# env.sh — Shared environment for all hooks
#
# TEMPLATE VERSION (claude-backup):
#   Contains ${PROJECT_REPO} / ${PLANNING_REPO} placeholders.
#   /onboard replaces these with literal paths when setting up a developer's machine.
#
# RUNTIME VERSION (project/.claude/hooks/):
#   Contains resolved literal paths. Generated by /onboard.
#   Do NOT edit manually — re-run /onboard to reconfigure.
#
# Usage (from any hook script):
#   source "$(dirname "$0")/env.sh"

PROJECT_REPO="${PROJECT_REPO}"
PLANNING_REPO="${PLANNING_REPO}"
DEVELOPER="UNCONFIGURED"

# Derived paths used by multiple hooks
PLANNING_DIR="${PLANNING_REPO}"
STATE_FILE="${PLANNING_DIR}/main/STATE.md"
HANDOVER_DIR="${PLANNING_DIR}/handovers"
DECISIONS_DIR="${PLANNING_DIR}/decisions"
BACKUP_COMMANDS_DIR="${PLANNING_DIR}/claude-backup/commands"

# --- Validation helper ---
# Call this from hooks that need the planning repo to exist.
# Usage: require_planning_repo || exit 0
require_planning_repo() {
  if [[ -z "$PLANNING_REPO" || "$PLANNING_REPO" == '${PLANNING_REPO}' ]]; then
    echo "Hook skipped: env.sh not configured. Run /onboard." >&2
    return 1
  fi
  if [[ ! -d "$PLANNING_REPO" ]]; then
    echo "Hook skipped: PLANNING_REPO not found at $PLANNING_REPO" >&2
    return 1
  fi
  return 0
}
